[config]
runs = 1

[green_agent]
agentbeats_id = "019c9839-7908-7f80-bd52-e7c3443fefd9"

[green_agent.env]
GREEN_TOKEN = "${GREEN_TOKEN}"

[[participants]]
agentbeats_id = "019c9839-7928-7d62-bb0d-006e8b6f8978"
name = "competitor"

[participants.env]
API_KEY = "${API_KEY}"