name: Quick Submit

on:
  pull_request:
    types: [opened, reopened]
    branches: [agentbeats-e2e-quick-submit-3f245ee1f8]

jobs:
  run-scenario:
    if: startsWith(github.head_ref, 'quick-submit-')
    uses: RDI-Foundation/agentbeats-leaderboard-template/.github/workflows/quick-submit-runner.yml@v2
    with:
      backend_url: "https://walks-satisfied-albert-remarkable.trycloudflare.com"
    permissions:
      id-token: write
      contents: write
      packages: read
