name: Quick Submit

on:
  pull_request:
    types: [opened, reopened]
    branches: [agentbeats-e2e-quick-submit-7ec988443a]

jobs:
  run-scenario:
    if: startsWith(github.head_ref, 'quick-submit-')
    uses: RDI-Foundation/agentbeats-leaderboard-template/.github/workflows/quick-submit-runner.yml@v1
    permissions:
      id-token: write
      contents: write
      packages: read
