name: Quick Submit

on:
  pull_request:
    types: [opened, reopened]
    branches: [agentbeats-e2e-quick-submit-6c6dc2199f]

jobs:
  run-scenario:
    if: startsWith(github.head_ref, 'quick-submit-')
    uses: RDI-Foundation/agentbeats-leaderboard-template/.github/workflows/quick-submit-runner.yml@v1
    with:
      backend_url: "https://adjustment-therapist-logic-brochure.trycloudflare.com"
    permissions:
      id-token: write
      contents: write
      packages: read
